Add scope field
rciam/comanage-registry-plugin-RcauthSource pull request #4
Opened 2020-08-06 13:22 UTC by lionick

Run the following query to add the new field at cm_rcauth_sources
`alter table cm_rcauth_sources add scopes varchar(256)`

2020-08-07 11:52 UTC, lionick commented on Console/Command/UpgradeVersionShell.php
> +               "alter table cm_rcauth_sources add scopes varchar(256)";
Done

2020-08-07 11:53 UTC, lionick commented on Console/Command/UpgradeVersionShell.php
> +               "alter table cm_rcauth_sources add scopes varchar(256)";
done

2020-08-08 09:37 UTC, ioigoume commented on Console/Command/UpgradeVersionShell.php
> +        if(!$err) {
This is not needed. Add the commit in the try block. As soon as an error is thrown then the catch block will take control

2020-08-08 09:38 UTC, ioigoume commented on Console/Command/UpgradeVersionShell.php
> +        $err = false;
Discard $err variable

2020-08-08 09:39 UTC, ioigoume commented on webroot/css/style.css
> +}
Add a new line character here

2020-08-08 09:40 UTC, ioigoume commented
@lionick rebase onto develop branch and resolve conflicts

2020-08-28 07:41 UTC, ioigoume requested changes

2020-08-28 07:41 UTC, ioigoume commented on View/RcauthSources/fields.inc
> +  <li class="field-flex">
Do we still need field-flex?

2020-08-28 07:41 UTC, ioigoume commented on webroot/css/style.css
> +ul.form-list li.field-flex {
Do we need the style.css file now that we do not use the checkbox list

2020-08-28 08:41 UTC, ioigoume commented
@lionick do not forget to update the README.md file regarding the way the user should upgrade

2020-08-29 09:02 UTC, ioigoume approved these changes

2020-08-29 09:03 UTC, merged